Style/Documentation:
  Enabled: false

# Line length is not useful
Metrics/LineLength:
  Enabled: false


# Due to legacy codebase
#   - Globals are used liberally
Style/GlobalVars:
  Enabled: false
#   - A lot of complexity
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
#   - Long Methods, Classes, Blocks, and Modules
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false


# Either sytnax for regex is ok
Style/RegexpLiteral:
  Enabled: false
# Intermediate variables are not always helpful
Style/MultilineBlockChain:
  Enabled: false

Style/FileName:
  Exclude:
    - 'lib/gettext-setup.rb'

Style/IndentHeredoc:
  Exclude:
    - 'lib/metadata_pot/metadata_pot.rb'

